[project]
name = "arlogi"
version = "0.607.24"
description = "Robust, type-safe and highly configurable logging library for Python"
readme = "README.md"
authors = [
    { name = "Anton Razumov", email = "arazumov@checkpoint.com" }
]
requires-python = ">=3.13"
dependencies = [
    "graphifyy",
    "rich>=14.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "commitizen>=4.0.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "radon>=6.0.1",
    "ruff>=0.14.10",
    "mkdocs-git-revision-date-localized-plugin>=1.5.0",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocs-material>=9.7.1",
    "mkdocstrings>=1.0.0",
    "mkdocstrings-python>=1.16.2",
    "pymdown-extensions>=10.19.1",
    "psutil>=7.2.1",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "pep621"
version_files = ["pyproject.toml"]
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"

[tool.uv.sources]
graphifyy = { git = "https://github.com/Graphify-Labs/graphify" }

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "--cov=src/arlogi --cov-report=term-missing --cov-report=json"

[tool.coverage.run]
source = ["src/arlogi"]
branch = true
